### ISSUE TITLE
Vulnerabilities with "npm install", asking npm to fix them breaks "npm run release"

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-gui#145]
This is very similar to #108.

`npm install` says it found vulnerabilities. Trying to fix them with `npm audit fix` will lead to errors wile running `npm run release`.

It also appears that some vulnerabilities are not automatically fixed and may involve breaking changes.

```
$ git branch                                                                                              
* develop                                                                                                                                     
  master
$ npm install
...
found 369 vulnerabilities (358 low, 11 high)
  run `npm audit fix` to fix them, or `npm audit` for details
$ npm audit fix
...
fixed 346 of 369 vulnerabilities in 2348 scanned packages
  21 vulnerabilities required manual review and could not be updated
  2 package updates for 2 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
$ npm run release
...
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-yTTdoZ/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! zonemaster-gui@3.2.0 build: `node scripts/faq.js && ng build --prod`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the zonemaster-gui@3.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zm/.npm/_logs/2020-10-22T13_16_37_637Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zonemaster-gui@3.2.0 release: `npm run build && node scripts/create_release.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zonemaster-gui@3.2.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zm/.npm/_logs/2020-10-22T13_16_37_798Z-debug.log
```

Et le fichier de log :

```
$ cat /home/zm/.npm/_logs/2020-10-22T13_16_37_798Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/zm/.nvm/versions/node/v13.12.0/bin/node',
1 verbose cli   '/home/zm/.nvm/versions/node/v13.12.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'release'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle zonemaster-gui@3.2.0~prerelease: zonemaster-gui@3.2.0
6 info lifecycle zonemaster-gui@3.2.0~release: zonemaster-gui@3.2.0
7 verbose lifecycle zonemaster-gui@3.2.0~release: unsafe-perm in lifecycle true
8 verbose lifecycle zonemaster-gui@3.2.0~release: PATH: /home/zm/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/zm/zonemaster-gui/node_modules/.bin:/home/zm/.nvm/versions/node/v13.12.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle zonemaster-gui@3.2.0~release: CWD: /home/zm/zonemaster-gui
10 silly lifecycle zonemaster-gui@3.2.0~release: Args: [ '-c', 'npm run build && node scripts/create_release.js' ]
11 silly lifecycle zonemaster-gui@3.2.0~release: Returned: code: 1  signal: null
12 info lifecycle zonemaster-gui@3.2.0~release: Failed to exec release script
13 verbose stack Error: zonemaster-gui@3.2.0 release: `npm run build && node scripts/create_release.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/zm/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/zm/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid zonemaster-gui@3.2.0
15 verbose cwd /home/zm/zonemaster-gui
16 verbose Linux 4.15.0-122-generic
17 verbose argv "/home/zm/.nvm/versions/node/v13.12.0/bin/node" "/home/zm/.nvm/versions/node/v13.12.0/bin/npm" "run" "release"
18 verbose node v13.12.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error zonemaster-gui@3.2.0 release: `npm run build && node scripts/create_release.js`
22 error Exit status 1
23 error Failed at the zonemaster-gui@3.2.0 release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by matsduf** [comment]
See #108

**Comment by sandoche2k** [comment]
Same error occured on CentOS 8 @pamasse

**Comment by matsduf** [comment]
> Same error occured on CentOS 8 @pamasse

@sandoche2k, do you have more details?

**Comment by sandoche2k** [comment]
The logs are same as what @pnax has in the beginning of the issue

**Comment by pnax** [comment]
See #146 for an almost* up to date dependencies list.

\* as mattias-p pointed out in https://github.com/zonemaster/zonemaster-gui/pull/146#pullrequestreview-519857833 dependencies versions are moving fast.

**Comment by sandoche2k** [comment]
The errors could be ignored since the `npm run release`creates the GUI zip file

**Comment by matsduf** [comment]
Will not fix.
