### ISSUE TITLE
Failing to build zonemaster_web_gui.zip

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#50]
I installed node.js/npm under Ubuntu 16.04. I followed the instructions in [nodesource/distributions] and everything looked good. I installed version 10.15.3. Then I tried to create the zip file from the zonemaster-gui develop branch and that did not work at all.

```
$ npm run release

> zonemaster-gui@3.0.1 release /home/matsd/git/zonemaster-gui
> npm run build && node scripts/create_release.js


> zonemaster-gui@3.0.1 build /home/matsd/git/zonemaster-gui
> node scripts/faq.js && ng build -prod

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'showdown'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/matsd/git/zonemaster-gui/scripts/faq.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zonemaster-gui@3.0.1 build: `node scripts/faq.js && ng build -prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zonemaster-gui@3.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matsd/.npm/_logs/2019-05-15T16_28_50_473Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zonemaster-gui@3.0.1 release: `npm run build && node scripts/create_release.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zonemaster-gui@3.0.1 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matsd/.npm/_logs/2019-05-15T16_28_50_509Z-debug.log
```

The created debug log file contains the following lines:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'release' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle zonemaster-gui@3.0.1~prerelease: zonemaster-gui@3.0.1
6 info lifecycle zonemaster-gui@3.0.1~release: zonemaster-gui@3.0.1
7 verbose lifecycle zonemaster-gui@3.0.1~release: unsafe-perm in lifecycle true
8 verbose lifecycle zonemaster-gui@3.0.1~release: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/matsd/git/zonemaster-gui/node_modules/.bin:/home/matsd/bin:/home/matsd/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle zonemaster-gui@3.0.1~release: CWD: /home/matsd/git/zonemaster-gui
10 silly lifecycle zonemaster-gui@3.0.1~release: Args: [ '-c', 'npm run build && node scripts/create_release.js' ]
11 silly lifecycle zonemaster-gui@3.0.1~release: Returned: code: 1  signal: null
12 info lifecycle zonemaster-gui@3.0.1~release: Failed to exec release script
13 verbose stack Error: zonemaster-gui@3.0.1 release: `npm run build && node scripts/create_release.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid zonemaster-gui@3.0.1
15 verbose cwd /home/matsd/git/zonemaster-gui
16 verbose Linux 4.4.0-145-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "release"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error zonemaster-gui@3.0.1 release: `npm run build && node scripts/create_release.js`
22 error Exit status 1
23 error Failed at the zonemaster-gui@3.0.1 release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

[nodesource/distributions]: https://github.com/nodesource/distributions/blob/master/README.md#deb

**Comment by pamasse** [comment]
Hi Mats,

I think you didn't install dependencies with the command `npm install`.
Run it in the folder when you are at the package.json level.

I will add a pre-release action which will (re)install the dependencies.

**Comment by matsduf** [comment]
You are correct. I misunderstood the command. I have started it now. It compiled a lot and ended with
```
Installed to /home/matsd/git/zonemaster-gui/node_modules/node-sass/vendor/linux-x64-64/binding.node
npm WARN zonemaster-gui@3.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1909 packages from 2340 contributors and audited 10861 packages in 194.256s
found 293 vulnerabilities (29 low, 178 moderate, 84 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Then I ran `npm run release` which outputed:

```
> zonemaster-gui@3.0.1 release /home/matsd/git/zonemaster-gui
> npm run build && node scripts/create_release.js

npm WARN invalid config loglevel="notice"

> zonemaster-gui@3.0.1 build /home/matsd/git/zonemaster-gui
> node scripts/faq.js && ng build -prod

{ [Error: ENOENT: no such file or directory, open './docs/FAQ/gui-faq-ru.md']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './docs/FAQ/gui-faq-ru.md' }

(...)
```

**Comment by pamasse** [comment]
The joy of using nodejs, there are a lot of dependencies. About "NPM WARN" messages, this is very very classical in nodejs and it can be ignored.
Also, NPM gives you some statistics like the number of packages installed and also check if there are known vulnerabilities on these packages. If you check these packages, you will see that they are about our dev environement and have not link with the gui. 
Here we use Nodejs to produce javascript application, but we could use only a simple edit tool like vim. Nodejs give us a lot of development tool.

I will check for 2019.2 to upgrade these dependencies.

About the gui-faq-ru.md, there are a simple heuristic which check the language available in "/src/assets/i18n" and then try to convert for all detected language the gui-faq-XX.md file. As we have a ru.json, the heuristic try to convert gui-faq-ru.md into gui-faq-ru.html.

**Comment by matsduf** [comment]
The original issue has been solved with the explanation from @pamasse .
